cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart/', views.view_cart, name='view_cart'),
    path('add_to_cart/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:item_id>/', views.update_cart, name='update_cart'),
    path('delete_from_cart/<int:item_id>/', views.delete_from_cart, name='delete_from_cart'),
]

eccomerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('cart/', include('cart.urls')),
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from item.models import Item

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ManyToManyField(Item, through='CartItem')

    def __str__(self):
        return f"{self.user.username}'s Cart"

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.cart.user.username}'s cart: {self.item.name}"

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cart, Item, CartItem
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from item.models import Category

@login_required
def view_cart(request):
    categories = Category.objects.all()
    try:
        cart = Cart.objects.get(user=request.user)
    except Cart.DoesNotExist:
        # Create a new cart for the user
        cart = Cart.objects.create(user=request.user)

    # Calculate the total price
    total_price = sum(cart_item.item.price * cart_item.quantity for cart_item in cart.cartitem_set.all())

    return render(request, 'cart/view_cart.html', {'cart': cart, 'categories': categories, 'total_price': total_price})


@login_required
def add_to_cart(request, item_id):
    item = Item.objects.get(id=item_id)

    # Get or create a cart for the user
    cart, created = Cart.objects.get_or_create(user=request.user)

    # Add the item to the cart
    cart_item, item_created = CartItem.objects.get_or_create(cart=cart, item=item)

    if not item_created:
        # Item already exists in the cart, increment the quantity
        cart_item.quantity += 1
        cart_item.save()
        messages.success(request, f"{item.name} quantity updated in your cart.")
    else:
        messages.success(request, f"{item.name} added to your cart.")

    return redirect('item:detail', item_id, )

@login_required
def update_cart(request, item_id):
    if request.method == 'POST':
        quantity = request.POST.get('quantity', 1)
        
        # Retrieve the user's cart
        try:
            cart = Cart.objects.get(user=request.user)
        except Cart.DoesNotExist:
            messages.error(request, 'Cart not found.')
            return redirect('cart:view_cart')

        # Update the cart item
        cart_item = CartItem.objects.get(cart=cart, item_id=item_id)
        cart_item.quantity = quantity
        cart_item.save()
        messages.success(request, 'Cart updated successfully.')
    
    # Redirect to the view_cart URL without passing categories as an argument
    return redirect('cart:view_cart')

@login_required
def delete_from_cart(request, item_id):
    if request.method == 'POST':
        # Retrieve the user's cart
        try:
            cart = Cart.objects.get(user=request.user)
        except Cart.DoesNotExist:
            messages.error(request, 'Cart not found.')
            return redirect('cart:view_cart')

        cart_item = get_object_or_404(CartItem, cart=cart, item_id=item_id)
        cart_item.delete()
        messages.success(request, 'Item removed from cart.')

    return redirect('cart:view_cart')

templates/cart/view_cart.html
{% extends "core/base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/item-cart.css' %}"> 

<h1 class="cart-header" style="margin-top:50px;">Your Cart</h1>
<div class="container">

    {% if cart.cartitem_set.all %}
        <ul class="item-ul">
            {% for cart_item in cart.cartitem_set.all %}
                <li class="item-li">
                    <div class="center-items">
                        <img class="cart-image" src="{{ cart_item.item.image.url }}" alt="{{ cart_item.item.name }}">
                        <p style="margin-left:10px;">{{ cart_item.item.name }}</p>
                        <p style="margin-left:15px;">{{ cart_item.item.price|floatformat:0 }} {{ cart_item.item.currency }}</p> 
                    </div>
                    <div>
                        <div class="quantity-container">
                            <form class="button-div" method="POST" action="{% url 'cart:update_cart' cart_item.item.id %}">
                                {% csrf_token %}
                                <button type="button" class="quantity-btn minus" onclick="updateCartQuantity('{{ cart_item.item.id }}', -1)">-</button>
                                <input type="number" id="quantity{{ cart_item.item.id }}" name="quantity" value="{{ cart_item.quantity }}" min="1" class="no-arrows" oninput="saveCartQuantity('{{ cart_item.item.id }}', this.value)">
                                <button type="button" class="quantity-btn plus-btn" onclick="updateCartQuantity('{{ cart_item.item.id }}', 1)">+</button>
                            </form>
                            <form method="POST" action="{% url 'cart:delete_from_cart' cart_item.item.id %}">
                                {% csrf_token %}
                                <button type="submit" class="remove-btn"><i class="fa-solid fa-trash"></i></button>
                            </form>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Your cart is empty.</p>
    {% endif %}

    {% if cart.cartitem_set.all %}
        <div class="full-price">
            <p>Total Price: {{ total_price|floatformat:2 }} <small>{{ cart.cartitem_set.first.item.currency }}</small></p>
            <a href="#"><button class="btn draw-border">PURCHASE</button></a>
        </div>
    {% endif %}
</div>



<script>
    function updateCartQuantity(itemId, amount) {
        var inputElement = document.getElementById('quantity' + itemId);
        var currentValue = parseInt(inputElement.value);
        var newValue = Math.max(1, currentValue + amount);

        // Update the quantity input value
        inputElement.value = newValue;

        // Save the updated quantity to localStorage
        saveCartQuantity(itemId, newValue);

        // Recalculate and update the total price
        recalculateTotalPrice();
    }

    function saveCartQuantity(itemId, value) {
        localStorage.setItem('quantity' + itemId, value);
    }

    function recalculateTotalPrice() {
        var total = 0;

        // Iterate through each item in the cart and calculate the total price
        {% for cart_item in cart.cartitem_set.all %}
            var quantity = parseInt(document.getElementById('quantity{{ cart_item.item.id }}').value);
            var price = parseFloat('{{ cart_item.item.price }}');
            var totalPrice = quantity * price;

            // Convert the price to GEL if the currency is USD
            if ('{{ cart_item.item.currency }}' === 'USD') {
                totalPrice *= exchangeRate;
            }

            total += totalPrice;
        {% endfor %}

        // Display the recalculated total price
        document.querySelector('.full-price p').innerText = 'Total Price: ' + total.toFixed(2) + ' GEL';
    }

    document.addEventListener('DOMContentLoaded', function () {
        // Retrieve and set saved values
        {% for cart_item in cart.cartitem_set.all %}
            var quantityValue = localStorage.getItem('quantity{{ cart_item.item.id }}');
            if (quantityValue !== null) {
                document.getElementById('quantity{{ cart_item.item.id }}').value = quantityValue;
            }
        {% endfor %}

        // Initial total price calculation
        recalculateTotalPrice();
    });
</script>


{% endblock content %}