cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart/', views.view_cart, name='view_cart'),
    path('add_to_cart/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:item_id>/', views.update_cart, name='update_cart'),
    path('delete_from_cart/<int:item_id>/', views.delete_from_cart, name='delete_from_cart'),
]

core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="core/login.html", authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('update_profile/', views.update_profile, name='update_profile'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

eccomerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('cart/', include('cart.urls')),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('category/<int:category_id>/', views.category_items, name='category_items'),
    path('user-items/', views.user_items, name='user_items'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'gender', 'mobile_number')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['gender'] = forms.ChoiceField(choices=self.GENDER_CHOICES, widget=forms.RadioSelect(attrs={'class': 'gender-field'}))
        self.fields['mobile_number'] = forms.CharField(max_length=15, required=False, widget=forms.TextInput(attrs={'placeholder': 'Mobile Number', 'class': 'mobile-number-field'}))


    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'username-field',
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email', 
        'class': 'email-field'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'password1-field',
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm password',
        'class': 'password2-field',
    }))

    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect(attrs={
        'class': 'gender-field'
    }))

    mobile_number = forms.CharField(max_length=15, required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Mobile Number',
        'class': 'mobile-number-field'
    }))
    
    
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': '',
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': '',
    }))


class UpdateProfileForm(UserChangeForm):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]
    class Meta:
        model = User
        fields = ['username', 'email', 'gender']

    password = None 

    username = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'username-field',
    }))

    email = forms.CharField(required=False, widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'email-field',
    }))

    gender = forms.ChoiceField(required=False, choices=GENDER_CHOICES, widget=forms.RadioSelect(attrs={
        'class': 'gender-field'
    }))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class PasswordChangeForm(PasswordChangeForm):
    class Meta:
        model = User

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs.update({'class': 'password-field', 'placeholder': 'Old Password'})
        self.fields['new_password1'].widget.attrs.update({'class': 'password-field', 'placeholder': 'New Password'})
        self.fields['new_password2'].widget.attrs.update({'class': 'password-field', 'placeholder': 'Confirm New Password'})

        self.fields['old_password'].required = False
        self.fields['new_password1'].required = False
        self.fields['new_password2'].required = False

core/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from item.models import Category,Item
from django.contrib.auth import update_session_auth_hash,logout
from .forms import SignUpForm, UpdateProfileForm, PasswordChangeForm
from django.contrib import messages


def index(request):
    items = Item.objects.filter(is_sold=False).order_by('-created_at')[:20]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })


def signup(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            return redirect('/login/', {'categories': categories})
        
    else:
        form = SignUpForm()

    return render(request, 'core/signup.html', {
        'form': form,
        'categories': categories,
    })


@login_required
def update_profile(request):
    user = request.user
    categories = Category.objects.all()

    if request.method == 'POST':
        profile_form = UpdateProfileForm(request.POST, instance=user)
        password_form = PasswordChangeForm(user, request.POST)

        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Profile updated successfully - Username changed')

        if password_form.is_valid():
            password_form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Password changed successfully')

            # Log out the user
            logout(request)

            return redirect(reverse('core:login', {'categories': categories}))

    else:
        profile_form = UpdateProfileForm(instance=user)
        password_form = PasswordChangeForm(user)

    return render(request, 'core/update_profile.html', {'profile_form': profile_form, 'password_form': password_form})

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@700&family=Teko&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@100;500&family=Outfit:wght@700&family=Teko&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <script src="https://kit.fontawesome.com/f2df5e73f5.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock title %}VAANSKII COMMERECE</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand logo" href="{% url "core:index" %}"> <img src="{% static "images/logo.png" %}" alt="vanski" class='logo-img'><small class="small-png">AANSKII COMMERCE</small></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      
        <form method="get" action="{% url 'item:items' %}" class="form-inline categories">
          {{ item_filter.form.as_p }}
          <input name="query" class="form-control" type="search" placeholder="Search" aria-label="Search">
          <div class="vertical-line"></div>
          <button class="search-btn" type="submit"><img src="{% static "images/search-btn.png" %}" alt="search" class="search-btn-img"></button>
        </form>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for category in categories %}
                  <div class="category-container">
                      <a href="{% url 'item:category_items' category.id %}" class="category-link">
                          <div class="category-box">
                              <h2 class="category-title">{{ category.name }}</h2>
                          </div>
                      </a>
                  </div>
              {% endfor %}
          </div>
        </li>

          </ul>

          <div class="cart-heart">
            <a href="{% url "item:new" %}" class="plus"><i class="fa-solid fa-plus"></i>New</a>
            <a class="login" href="{% url 'cart:view_cart' %}"><i class="fa-solid fa-cart-shopping cart"></i>Cart</a>
          </div>
          {% if request.user.is_authenticated %}

          <div>
            <a class='login' href="{% url "core:update_profile" %}"><i class="fa-solid fa-circle-user"></i>{{ user.username }}</a>
            <a class="login" href="{% url "item:user_items" %}"><i class="fa-solid fa-cloud-arrow-up"></i> Your items</a>
          </div>
          <div class="auth">
            <a class="login" href="{% url "core:logout" %}"><i class="fa-solid fa-right-from-bracket"></i> Logout</a>
          </div>
          {% else %}
          <div>
            <a class="login" href="{% url "core:login" %}"><i class="fa-solid fa-user user-"></i>Log in</a>
            <a class="register" href="{% url "core:signup" %}"><i class="fa-solid fa-user-plus"></i>Sign up</a>
          </div>
          {% endif %}
        </div>
      </nav>

      
    {% block content %}{% endblock content %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
  
</body>
</html>

templates/core/filtered_items.html
<!-- filtered_items.html -->
<h1>Filtered Items for {{ category.name }}</h1>

{% for item in items %}
    <!-- Display item information here -->
    <p>{{ item.name }}, {{ item.price }}</p>
{% endfor %}

templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome | {% endblock %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/indexs.css' %}">
    
    <div class="body-container">
        <div class="full-container">
            <h2 class="text-center">Newest items</h2>
    
            <div class="items-container">
                {% for item in items %}
                    <div style="max-width:250px">
                        <a class="no-underline" href="{% url 'item:detail' item.id %}">
                            <img src="{{ item.image.url }}" class="image">
                            <div class="text-div">
                                <h2 class="text-name">{{ item.name }}</h2>
                                <p class="text-price">Price: {{ item.price|floatformat:0 }} {{ item.currency }} </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>


{% endblock %}

templates/core/login.html
{% extends "core/base.html" %}

{% block title %}Login | {% endblock title %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

<div class="container">
    <h1 class="login-h1">Authorization</h1>

    <form action="" method="post">
        {% csrf_token %}

        <div class="">
            {{ form.username }}
        </div>

        <div class="">
            {{ form.password }}
            <input type="checkbox" id="showPassword">
        </div>


        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ from.non_field_errors }}
            </div>
        {% endif %}

                    
        {% if form.errors or form.non_field_errors %}
            <div class="">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="btn draw-border">Submit</button>

        <p class='signup-link'>Do not have an account?<a href="{% url "core:signup" %}">Sign up</a></p>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Function to toggle password visibility
        function togglePasswordVisibility(inputId, checkboxId) {
            const passwordInput = document.getElementById(inputId);
            const showPasswordCheckbox = document.getElementById(checkboxId);

            showPasswordCheckbox.addEventListener('change', function () {
                if (showPasswordCheckbox.checked) {
                    passwordInput.type = 'text';
                } else {
                    passwordInput.type = 'password';
                }
            });
        }

        // Toggle visibility for the password field
        togglePasswordVisibility('{{ form.password.id_for_label }}', 'showPassword');
    });
</script>
{% endblock content %} 

templates/core/signup.html
{% extends "core/base.html" %}

{% block title %}Sign Up | {% endblock title %}

{% block content %} 

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">

    <div class="container">
        <h1 class="join-h1">Join Our Community</h1>
        <form action="" method="post">
            {% csrf_token %}

            <div class="">
                {{ form.username }}
            </div>

            <div class="">
                {{ form.mail }}
            </div>

            <div class="">
                {{ form.password1 }}
                <input type="checkbox" id="showPassword1">
            </div>

            <div class="">
                {{ form.password2 }}
                <input type="checkbox" id="showPassword2">
            </div>

            <div class="">
                <label class="gender" for="">Gender</label><br>
                {{ form.gender }}
            </div>            

            <div class="">
                {{ form.email }}
            </div>

            <div class="">
                {{ form.mobile_number }}
            </div>


            
            {% if form.errors or form.non_field_errors %}
                <div class="">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="btn draw-border">SUBMIT</button>
            <p class="login-link">Already have an account? <a href="{% url "core:login" %}">Login</a></p>
        </form>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Function to toggle password visibility
            function togglePasswordVisibility(inputId, checkboxId) {
                const passwordInput = document.getElementById(inputId);
                const showPasswordCheckbox = document.getElementById(checkboxId);
    
                showPasswordCheckbox.addEventListener('change', function () {
                    if (showPasswordCheckbox.checked) {
                        passwordInput.type = 'text';
                    } else {
                        passwordInput.type = 'password';
                    }
                });
            }
    
            // Toggle visibility for both password fields
            togglePasswordVisibility('{{ form.password1.id_for_label }}', 'showPassword1');
            togglePasswordVisibility('{{ form.password2.id_for_label }}', 'showPassword2');
        });
    </script>
</script>
{% endblock content %} 

templates/core/update_profile.html
{% extends "core/base.html" %}

{% block title %}Update Profile | {% endblock title %}

{% block content %} 

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">

    <div class="container">
        <h1 class="update-h1" style="font-family: 'Josefin Sans', sans-serif;font-family: 'Outfit', sans-serif;font-family: 'Teko', sans-serif; color:gray; margin-top:20px;margin-bottom:30px;">Update Your Profile</h1>
        <form action="{% url 'core:update_profile' %}" method="post">
            {% csrf_token %}

            <div class="form-group">
                {{ profile_form.username }}
            </div>

            <div class="form-group">
                {{ profile_form.email }}
            </div>

            <div class="form-group">
                {{ password_form.old_password }}
                <input type="checkbox" id="showPassword" />
            </div>

            <div class="form-group">
                {{ password_form.new_password1 }}
                <input type="checkbox" id="showPassword1" />
            </div>

            <div class="form-group">
                {{ password_form.new_password2 }}
                <input type="checkbox" id="showPassword2" />
            </div>

            <button class="btn draw-border" type="submit">UPDATE</button>
        </form>
    </div>

    <script>
        // Function to toggle password visibility
        function togglePasswordVisibility(inputId, checkboxId) {
            const passwordInput = document.getElementById(inputId);
            const showPasswordCheckbox = document.getElementById(checkboxId);

            showPasswordCheckbox.addEventListener('change', function () {
                if (showPasswordCheckbox.checked) {
                    passwordInput.type = 'text';
                } else {
                    passwordInput.type = 'password';
                }
            });
        }

        // Toggle visibility for both password fields
        togglePasswordVisibility('{{ password_form.old_password.id_for_label }}', 'showPassword');
        togglePasswordVisibility('{{ password_form.new_password1.id_for_label }}', 'showPassword1');
        togglePasswordVisibility('{{ password_form.new_password2.id_for_label }}', 'showPassword2');
    </script>

{% endblock content %}