cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart/', views.view_cart, name='view_cart'),
    path('add_to_cart/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:item_id>/', views.update_cart, name='update_cart'),
    path('delete_from_cart/<int:item_id>/', views.delete_from_cart, name='delete_from_cart'),
]

eccomerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('cart/', include('cart.urls')),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('category/<int:category_id>/', views.category_items, name='category_items'),
    path('user-items/', views.user_items, name='user_items'),
]

item/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255)
    
    class Meta:
        ordering = ('name', )
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    


class Item(models.Model):
    category = models.ForeignKey(Category, related_name = 'items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name = 'items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    currency = models.CharField(max_length=3, choices=[('USD', '$'), ('GEL', '₾')], default='USD')

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    

item/forms.py
from django import forms
from .models import Item

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image', 'currency')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['category'].label = 'Category:'
        self.fields['category'].widget.attrs.update({'class': 'category-class'})

        self.fields['name'].label = 'Item Name:'
        self.fields['name'].widget.attrs.update({'class': 'name-class'})

        self.fields['description'].label = 'Description:'
        self.fields['description'].widget.attrs.update({'class': 'description-class'})

        self.fields['price'].label = 'Price:'
        self.fields['price'].widget.attrs.update({'class': 'price-class'})

        self.fields['image'].label = 'Upload image:'
        self.fields['image'].widget.attrs.update({'class': 'image-class'})

        self.fields['currency'].widget.attrs.update({'class': 'currency-class'})
        self.fields['currency'].widget = forms.RadioSelect(choices=[('USD', '$'), ('GEL', '₾')])


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image', 'currency', 'is_sold')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['category'].label = 'Category:'
        self.fields['category'].widget.attrs.update({'class': 'category-class'})

        self.fields['name'].label = 'Item Name:'
        self.fields['name'].widget.attrs.update({'class': 'name-class'})

        self.fields['description'].label = 'Description:'
        self.fields['description'].widget.attrs.update({'class': 'description-class'})

        self.fields['price'].label = 'Price:'
        self.fields['price'].widget.attrs.update({'class': 'price-class'})

        self.fields['image'].label = 'Upload image:'
        self.fields['image'].widget.attrs.update({'class': 'image-class'})

        self.fields['currency'].widget.attrs.update({'class': 'currency-class'})
        self.fields['currency'].widget = forms.RadioSelect(choices=[('USD', '$'), ('GEL', '₾')])

        self.fields['is_sold'].label = 'Sold:'
        self.fields['is_sold'].widget.attrs.update({'class': 'image-class'})

item/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Item, Category
from .forms import NewItemForm, EditItemForm


def category_items(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    items = Item.objects.filter(category=category)
    categories = Category.objects.all()

    return render(request, 'item/category_items.html', {'category': category, 'items': items, 'categories': categories})

def items(request):

    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id )

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    result_count = items.count()

    return render(request, 'item/items.html', {
        'items':items,
        'query':query,
        'categories':categories,
        'category_id': int(category_id),
        'result_count': result_count
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[:10]
    categories = Category.objects.all()

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items,
        'categories' : categories,
    })


@login_required
def new(request):
    categories = Category.objects.all()
    if request.method == "POST":
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New Item | ',
        'categories' : categories,
    })


@login_required
def edit(request, pk):
    categories = Category.objects.all()
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/update-item.html', {
        'form': form,
        'title': 'Edit Item',
        'categories' : categories,
    })

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('core:index')

@login_required
def user_items(request):
    categories = Category.objects.all()
    user_uploaded_items = Item.objects.filter(created_by=request.user)
    print("user_uploaded_items:", user_uploaded_items)

    if user_uploaded_items.exists():
        return render(request, 'item/user_items.html', {'user_uploaded_items': user_uploaded_items,'categories' : categories,})
    else:
        return render(request, 'item/user_items.html', {'categories' : categories,})

templates/item/category_items.html
{% extends "core/base.html" %}
{% block title %}{{ category.name }} | {% endblock title %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/category-items.css' %}"> 
<h1 class="text-center">Items in {{ category.name }} category</h1>

{% if items %}
    <div class="item-container">
        <div class="item-grid">
            {% for item in items %}
                <div class="item">
                    <a class="no-underline" href="{% url 'item:detail' item.id %}">
                        <img class="search-image" src="{{ item.image.url }}">
                        <h2 class="text-name">{{ item.name }}</h2>
                        <p class="text-price">Price: {{ item.price|floatformat:0 }} {{ item.currency }}</p>
                    </a>
                </div>
                {% endfor %}
        </div>
    </div>
{% else %}
<h3 class="text-center">There is not items in this category</h3>
{% endif %}
{% endblock content %}

templates/item/detail.html
{% extends "core/base.html" %}

{% block title %} {{ item.name }} Detail | {% endblock title %}


{% block content %}
    {% load static %} 
    <link rel="stylesheet" href="{% static 'css/details.css' %}"> 

    <div class="container">
        <div class="image-div">
            <img class="detail-img" src="{{ item.image.url }}">
        </div>


        <div class="details">
            <h1 class="detail-name" >{{ item.name }}</h1> <hr>
            <p class="detail-price"><strong>Price: </strong>{{ item.price|floatformat:0 }} {{ item.currency }}</p>
            <p class="detail-seller"><strong>Seller: </strong>{{ item.created_by }}</p>
            
            {% if item.description %}
                <p class="detail-description"> <strong>Description: </strong>  <br> {{ item.description }} </p>
            {% endif %}
            
        
            {% if request.user == item.created_by %}
                <div>
                    <p>This is your item! You can delete or edit it.</p>
                    <a class="edit-btn" href="{% url "item:edit" item.id %}">Edit</a>
                    <a class="delete-btn"href="{% url "item:delete" item.id %}">Delete</a>
                </div>
            {% else %}


            {% if request.user != item.created_by %}
                <a class="add-to-cart-btn" href="{% url 'cart:add_to_cart' item.id %}">Add to cart</a>
            {% endif %}
        
            {% endif %}
        </div>
    </div>
    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}

    <hr style="margin-top: 100px;">

    {% if related_items %}
    <div class="related-items-container">
        <div class="full-container">
            <h2 class="text-center">Similar products</h2>
    
            <div class="items-container">
                {% for item in related_items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <img src="{{ item.image.url }}" class="image">
                            <div class="text-div">
                                <h2 class="text-name">{{ item.name }}</h2>
                                <p class="text-price">Price: {{ item.price|floatformat:0 }}$</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}


    

{% endblock content %}

templates/item/form.html
{% extends "core/base.html" %}

{% block title %} {{ title }} {% endblock title %}

{% block content %}
    {% load static %} 
    <link rel="stylesheet" href="{% static 'css/new-items.css' %}"> 

    <div class="container">
        <div class="justify-content-center">
            <div class="col-md-6" style="margin-left: 120px;">
                <h1 class="new-item" style="margin-right:10px;">Add Item</h1>

                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="{{ form.category.id_for_label }}" class="your-label-class">{{ form.category.label }}</label>
                        {{ form.category }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.name.id_for_label }}" class="your-label-class">{{ form.name.label }}</label>
                        {{ form.name }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.description.id_for_label }}" class="your-label-class">{{ form.description.label }}</label>
                        {{ form.description }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.image.id_for_label }}" class="your-label-class">{{ form.image.label }}</label>
                        {{ form.image }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.price.id_for_label }}" class="your-label-class">{{ form.price.label }}</label>
                        {{ form.price }} {{ form.currency }}
                    </div>


                    {% if form.errors or form.non_field_errors %}
                        <div class="alert alert-danger mt-3">
                            {% for field in form %}
                                {{ field.errors }}
                            {% endfor %}
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}

                    <button class="btn draw-border">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/item/items.html
{% extends "core/base.html" %}

{% block title %}Searching | {% endblock title %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/search-item.css' %}"> 

    <div class="item-container">
        {% if result_count %}
            <p>{{ result_count }} Results found.</p>
        {% else %}
            <p>No results found</p>
        {% endif %}
        
        <div class="item-grid">
            {% for item in items %}
                <div class="item">
                    <a class="no-underline" href="{% url 'item:detail' item.id %}">
                        <img class="search-image" src="{{ item.image.url }}">
                        <h2 class="text-name">{{ item.name }}</h2>
                        <p class="text-price">Price: {{ item.price|floatformat:0 }} {{ item.currency }}</p>
                    </a>
                </div>
                {% endfor %}
                <a href="{% url "item:items" %}">Clear filter</a>
        </div>
    </div>
{% endblock content %}

templates/item/update-item.html
{% extends "core/base.html" %}

{% block title %} {{ title }} {% endblock title %}

{% block content %}
    {% load static %} 
    <link rel="stylesheet" href="{% static 'css/new-items.css' %}"> 

    <div class="container">
        <div class="justify-content-center">
            <div class="col-md-6" style="margin-left: 120px;">
                <h1 class="new-item" style="margin-right:10px;">Update Item</h1>

                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="{{ form.category.id_for_label }}" class="your-label-class">{{ form.category.label }}</label>
                        {{ form.category }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.name.id_for_label }}" class="your-label-class">{{ form.name.label }}</label>
                        {{ form.name }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.description.id_for_label }}" class="your-label-class">{{ form.description.label }}</label>
                        {{ form.description }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.price.id_for_label }}" class="your-label-class">{{ form.price.label }}</label>
                        {{ form.price }} {{ form.currency }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.is_sold.id_for_label }}" class="your-label-class">{{ form.is_sold.label }}</label>
                        {{ form.is_sold }}
                    </div>


                    {% if form.errors or form.non_field_errors %}
                        <div class="alert alert-danger mt-3">
                            {% for field in form %}
                                {{ field.errors }}
                            {% endfor %}
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}

                    <button class="btn draw-border">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/item/user_items.html
  {% extends 'core/base.html' %}
  
  {% block content %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/search-item.css' %}"> 
  <h2 style="color:lightgray; text-align:center;margin-top:50px; margin-bottom:70px;">Your Uploaded Items</h2>
  
  
  <div class="item-container">
      <div class="item-grid">
          {% for item in user_uploaded_items %}
          <div class="item">
              <a class="no-underline" href="{% url 'item:detail' item.id %}">
                  <img class="search-image" src="{{ item.image.url }}">
                  <h2 class="text-name">{{ item.name }}</h2>
                  <p class="text-price">Price: {{ item.price|floatformat:0 }} {{ item.currency }}</p>
                </a>
            </div>
            {% endfor %}
        </div>
        <p style="color:gray; text-align:center;margin-top:50px; margin-bottom:70px; font-size:50px;">You haven't uploaded any items yet. </p><br>
        <p style="color:gray; text-align:center;margin-top:50px; margin-bottom:70px;"><a style="color:black; text-align:center;margin-top:50px; margin-bottom:70px;" href="{% url "item:new" %}">Click here</a> to add new items </p>
    </div>
    {% endblock %}
    
    